/*
@TP4.sql
*/

SET SERVEUROUTPUT ON;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE AB_NB';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

--num_abo:=&num_abo;
CREATE TABLE AB_NB(
    NUMERO NUMERIC(6,0) ,
    NB NUMERIC(3,0),
    CONSTRAINT PK_AB_NB PRIMARY KEY(NUMERO),
    CONSTRAINT FK_NUM_AB FOREIGN KEY(NUMERO) REFERENCES ABONNE(NUM_AB)
);
DECLARE
    num_abo ABONNE.NUM_AB%TYPE;
    nbr_abo AB_NB.NB%TYPE;
    num_abo2 ABONNE.NUM_AB%TYPE;
    AUCUN_EMPRUNT EXCEPTION;
BEGIN
    DBMS_OUTPUT.enable;
    num_abo:=&num_abo;
    SELECT NUM_AB INTO num_abo2 FROM ABONNE WHERE NUM_AB=num_abo;
    
    SELECT COUNT(*) INTO nbr_abo FROM EMPRUNT 
    WHERE EMPRUNT.NUM_AB=num_abo;

    IF nbr_abo=0 THEN RAISE AUCUN_EMPRUNT;
    ELSE INSERT INTO AB_NB VALUES(num_abo,nbr_abo);
    END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('numero ' || num_abo || ' invalide');
        INSERT INTO AB_NB VALUES(nbr_abo,NULL);

        WHEN AUCUN_EMPRUNT THEN
        DBMS_OUTPUT.PUT_LINE('aucun emprunt pour ' || num_abo );
        INSERT INTO AB_NB VALUES(nbr_abo,-1);
END;
/

SELECT * FROM AB_NB;