/*
-- ABONNE (NUM_AB, NOM, PRENOM, VILLE, AGE, TARIF, REDUC)
-- EXEMPLAIRE (NUMERO, DATE_ACHAT, PRIX, CODE_PRET, ETAT, ISBN)
-- LIVRE (ISBN, TITRE, SIECLE, CATEGORIE)
-- MOT_CLEF (MOT,#MOT)
-- EMPRUNT (NUM_AB, NUM_EX, D_EMPRUNT, D_RETOUR, D_RET_REEL, NB_RELANCE)
-- CARACTERISE (ISBN, MOT)
*/
ALTER TABLE ABONNE ADD(
    DATE_NAI DATE,
    TYPE_AB VARCHAR2(6),
    CAT_AB VARCHAR2(12),
    CONSTRAINT DOM_TYPE_AB CHECK 
        (TYPE_AB IN ('ENFANT','ADULTE')),
    CONSTRAINT DOM_CAT_AB CHECK
        (CAT_AB IN ('REGULIER','OCCASIONNEL','A PROBLEME','EXCLU'))

);